version: "2"
services:
  server:
    image : dgoldstein1/websiteanalytics-backend
    environment:
      - LOGGER=true
      - TEST_MODE=true
      - DATABASE_URL=mongodb://mongodb:27017
      - PORT=5000
      - BACKGROUND_LOOKUP_ENABLED=true
      - BACKGROUND_LOOKUP_INTERVAL=1 # one second
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - '5000:5000'
  mongodb:
    image: 'mongo:4.2.11'
    ports:
      - '27017:27017'