version: "2"
services:
  server:
    image : dgoldstein1/websiteanalytics-backend
    environment:
      - LOGGER=true
      - TEST_MODE=true
      - DATABASE_URL=mongodb+srv://dbuser1:password1@cluster0.pknpw.mongodb.net/links-visits
      - PORT=5000
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - '5000:5000'
  mongodb:
    image: 'mongo:4.2.11'
    ports:
      - '27017:27017'
    # volumes:
    #   - ./docker/mongodb/data/db:/data/db
    # environment:
    #   - MONGO_DATA_DIR=/data/db
    #   - MONGO_LOG_DIR=/dev/null
    # command: 'mongod --logpath=/dev/null'
