version: "3"
services:
  server:
    build: .
    environment:
      - LOGGER=true
      - TEST_MODE=true
      - DATABASE_URL=mongodb://mongodb:27017
      - PORT=5000
    links:
      - mongodb
    depends_on:
      - mongodb
    # volumes:
    #   - '.:/go/src/github.com/dgoldstein1/websiteAnalytics-backend'
    ports:
      - '5000:5000'
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: 'mongod --smallfiles --logpath=/dev/null'
