
defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/dgoldstein1/websiteanalyitcs-backend
  environment:
    GO111MODULE: "on"

version: 2
jobs:

  ###################
  ## Core Utilties ##
  ###################

  # build go binary and save it to workspace
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go build -o build/websiteanalyitcs-backend
      - run: build/websiteanalyitcs-backend --version
      - persist_to_workspace:
          root: .
          paths:
            - ./build/websiteanalyitcs-backend


  ############################
  ## Tasks for New Releases ##
  ############################

  push-docker-image:
    machine : true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name : "build and push docker images"
          command : |
              export $(cat VERSION | xargs)
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker build . -t dgoldstein1/websiteanalyitcs-backend:$VERSION -t dgoldstein1/websiteanalyitcs-backend:latest
              docker push dgoldstein1/websiteanalyitcs-backend:$VERSION
              docker push dgoldstein1/websiteanalyitcs-backend:latest

              docker login --username=$EMAIL --password=$HEROKU_API_KEY registry.heroku.com
              docker tag dgoldstein1/websiteanalyitcs-backend:$VERSION registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web

  heroku:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "deploy"
          command: |
              wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
              heroku version
              heroku container:release web --app $HEROKU_APP_NAME

  # publish github release with binary
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      # get binaries
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            export $(cat VERSION | xargs)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/websiteanalyitcs-backend


workflows:
  version: 2
  build-deploy:
    jobs:

      - build
      - push-docker-image:
          requires:
            - build
          filters:
            branches:
              only: master

      - publish-github-release:
          requires:
            - push-docker-image        
          filters:
            branches:
              only: master

      - heroku:
          requires:
            - push-docker-image
          filters:
            branches:
              only: master
